dist: xenial   # required for Python >= 3.7
language: python
python:
  - "3.6"
  - "3.7"

before_install:
  - sudo apt-get update

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r requirements_dev.txt
# command to run tests
script:
  python runtests.py

after_success:
  - coveralls